game:fonction.o main.o
	gcc fonction.o main.o -o game -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
fonction.o:fonction.c
	gcc -c fonction.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_ttf -lSDL_image -lSDL_mixer -g
